title: My Mind Map
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A virtual proof that I'm awesome
theme: jekyll-theme-cayman
