---

title: My Mind Map

# Short description of your site
description: A virtual proof that I'm awesome

timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-cayman
